### PR TITLE
add arm64 arch for docker build 

### PR DESCRIPTION
**Pull request by elopsod**

### CODE REVIEW

**Comment by elopsod** [comment]
@jonasvinther hi
Please take a look on this one
Totally forgot about docker build for multi arch

**Comment by elkh510** [comment]
hi @jonasvinther 
first of all i want to thank you for your work
`medusa` is very helpful tool
could you please merge this [PR](https://github.com/jonasvinther/medusa/pull/160)?
we are moving to **ARM** arch and docker for arm will be very useful
Thanks you!

**Review by jonasvinther — APPROVED** [review]

**Comment by jonasvinther** [comment]
Hi @elkh510 
There is a new version containing the docker arm version.

**Comment by elkh510** [comment]
@jonasvinther thanks a lot!

**Pull request merged**
