### PR TITLE
set tag into variable "Version" when docker build

### PR DESCRIPTION
**Pull request by elopsod**
hi

comand `medusa version` return `medusa development` on every docker image

```
docker run  -it ghcr.io/jonasvinther/medusa:0.4.0 version
medusa development

docker run  -it ghcr.io/jonasvinther/medusa:0.7.0 version
medusa development
```

### CODE REVIEW

**Comment by elopsod** [comment]
Hi @jonasvinther 
Could you please take a look ?

**Review by jonasvinther — APPROVED** [review]

**Comment by elopsod** [comment]
@jonasvinther could you please merge
Because of pipeline licence [error](https://github.com/jonasvinther/medusa/actions/runs/9146431527/job/25215688233?pr=159)
`{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected time to availability: 1047s.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached.`

**Comment by elopsod** [comment]
@jonasvinther 
sorry for interrupting
could you please run the [pipeline](https://github.com/jonasvinther/medusa/actions/workflows/release-docker.yml)

**Comment by elopsod** [comment]
@jonasvinther many thanks!

**Pull request merged**
